// @ts-check
import eslint from '@eslint/js';
import eslintPluginPrettierRecommended from 'eslint-plugin-prettier/recommended';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      'node_modules/',
      'dist/',
      'build/',
      'coverage/',
      '.nyc_output/',
      '.cache/',
      '.eslintcache',
      '.nestjs/',
      '.turbo/',
      '.next/',
      '.nuxt/',
      '.output/',
      '.vercel/',
      'generated/',
      'prisma/generated/',
      'src/generated/',
      '**/*.generated.*',
      '**/*.gen.*',
      'prisma/migrations/',
      '*.db',
      '*.sqlite',
      '*.sqlite3',
      'logs/',
      '*.log',
      'npm-debug.log*',
      'yarn-debug.log*',
      'yarn-error.log*',
      'pnpm-debug.log*',
      '.env',
      '.env.*',
      '!.env.example',
      '!.env.sample',
      'yarn.lock',
      'package-lock.json',
      'pnpm-lock.yaml',
      'bun.lockb',
      '.git/',
      '.github/',
      'docs/',
      '*.md',
      'LICENSE',
      'CODE_OF_CONDUCT.md',
      'CONTRIBUTING.md',
      'SECURITY.md',
      '*.http',
      'api.http',
      '*.config.js',
      '*.config.cjs',
      '*.config.mjs',
      'commitlint.config.js',
      'eslint.config.mjs',
      'nest-cli.json',
      'jest.config.js',
      'jest.config.cjs',
      'jest.config.mjs',
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  eslintPluginPrettierRecommended,
  {
    languageOptions: {
      globals: {
        ...globals.node,
        ...globals.jest,
      },
      sourceType: 'commonjs',
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-floating-promises': 'warn',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/unbound-method': 'off',
    },
  },
);
